'use client';
import { useEditorScroll } from './use-editor-scroll';
import { saveCandidate } from '@/app/actions/admin';
import { categoryOptions } from '@/lib/catalog';
import { questionTypeLabels,difficultyLabels } from '@/lib/labels';
import { competencies } from '@/lib/competencies';
import type { SourceCandidate,QuestionCandidate } from '@/types/source';
import type { Category } from '@/types/category';
import { Field,MultiSelect,Feedback,useAdminMutation,formText,formList,formScore } from './editor-fields';
export function CandidateEditor({candidate,sources,categories,onSaved,onCancel}:{candidate?:QuestionCandidate;sources:SourceCandidate[];categories:Category[];onSaved:()=>void;onCancel:()=>void}) {
 const {run,pending,result}=useAdminMutation(),editorRef=useEditorScroll<HTMLElement>();
 return <section ref={editorRef} className="panel section-padding mt-5 scroll-mt-6"><h2>{candidate?'Edit candidate':'Create candidate'}</h2><form className="space-y-4 mt-5" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);run(()=>saveCandidate(candidate?.id??null,{sourceId:formText(d,'source')||null,suggestedTitle:formText(d,'title'),suggestedScenario:formText(d,'scenario'),suggestedQuestion:formText(d,'question'),suggestedCategoryIds:formList(d,'categories'),questionType:formText(d,'type'),competencyIds:formList(d,'competencies'),difficulty:formText(d,'difficulty'),candidateScore:formScore(d,'score'),status:formText(d,'status'),notes:formText(d,'notes')}),()=>onSaved());}}><fieldset disabled={pending} className="space-y-4"><Field label="Source (optional)"><select name="source" defaultValue={candidate?.sourceId??''}><option value="">Original idea — no external source</option>{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></Field><Field label="Suggested title"><input name="title" required maxLength={500} defaultValue={candidate?.suggestedTitle}/></Field><Field label="Suggested scenario"><textarea name="scenario" rows={4} maxLength={30000} defaultValue={candidate?.suggestedScenario}/></Field><Field label="Suggested question"><textarea name="question" rows={3} maxLength={30000} defaultValue={candidate?.suggestedQuestion}/></Field><MultiSelect label="Suggested categories" name="categories" value={candidate?.suggestedCategoryIds??[]} options={categoryOptions(categories).map(c=>({id:c.id,name:'— '.repeat(c.depth)+c.name}))}/><div className="grid sm:grid-cols-2 gap-4"><Field label="Question type"><select name="type" defaultValue={candidate?.questionType??'applied'}>{Object.entries(questionTypeLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><Field label="Difficulty"><select name="difficulty" defaultValue={candidate?.difficulty??'intermediate'}>{Object.entries(difficultyLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field></div><MultiSelect label="Competencies" name="competencies" value={candidate?.competencyIds??[]} options={competencies}/><Field label="Candidate score (optional)"><input type="number" name="score" min={0} max={100} step={1} defaultValue={candidate?.candidateScore??''}/></Field><Field label="Status"><select name="status" defaultValue={candidate?.status??'pending_review'}><option value="pending_review">Pending Review</option><option value="rejected">Rejected</option></select></Field><Field label="Notes"><textarea name="notes" rows={3} maxLength={10000} defaultValue={candidate?.notes}/></Field><div className="flex flex-wrap gap-3"><button type="submit" className="button button-primary">{pending?'Saving…':'Save candidate'}</button><button type="button" className="button button-secondary" onClick={onCancel}>Cancel</button></div></fieldset><Feedback result={result}/></form></section>;
}
