'use client';
import { useState } from 'react';
import type { Category } from '@/types/category';
import { categoryOptions,categoryDescendants } from '@/lib/catalog';
import { saveCategory,deleteCategory } from '@/app/actions/admin';
import { Field,Feedback,useAdminMutation,formText } from './editor-fields';
export function CategoryManager({categories}:{categories:Category[]}) {
 const [id,setId]=useState(''),{run,pending,result}=useAdminMutation(),selected=categories.find(c=>c.id===id);
 const forbidden=new Set(id?categoryDescendants(categories,id):[]);if(id)forbidden.add(id);
 return <section className="panel section-padding mt-5"><h2>Manage categories</h2><p className="muted text-sm mt-2">IDs stay stable. Categories used by content or child categories cannot be deleted.</p><div className="mt-5"><Field label="Category to edit"><select value={id} onChange={e=>setId(e.target.value)}><option value="">Create a new category</option>{categoryOptions(categories).map(c=><option key={c.id} value={c.id}>{'— '.repeat(c.depth)}{c.name}</option>)}</select></Field></div><form key={JSON.stringify(selected??null)} className="space-y-4 mt-5" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);run(()=>saveCategory(id||null,{slug:formText(d,'slug'),name:formText(d,'name'),description:formText(d,'description'),parentId:formText(d,'parent'),sortOrder:Number(formText(d,'order'))}),r=>r.id&&setId(r.id));}}><fieldset className="space-y-4" disabled={pending}><Field label="Name"><input name="name" defaultValue={selected?.name} required maxLength={500}/></Field><Field label="Slug"><input name="slug" defaultValue={selected?.slug} required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={150}/></Field><Field label="Parent category"><select name="parent" defaultValue={selected?.parentId??''}><option value="">Root category</option>{categoryOptions(categories).filter(c=>!forbidden.has(c.id)).map(c=><option key={c.id} value={c.id}>{'— '.repeat(c.depth)}{c.name}</option>)}</select></Field><Field label="Description"><textarea name="description" rows={3} defaultValue={selected?.description??''} maxLength={10000}/></Field><Field label="Sort order"><input name="order" type="number" step={1} required defaultValue={selected?.sortOrder??0}/></Field><div className="flex gap-3"><button type="submit" className="button button-primary">Save category</button>{selected&&<button type="button" className="button button-secondary" onClick={()=>run(()=>deleteCategory(selected.id),()=>setId(''))}>Delete unused category</button>}</div></fieldset><Feedback result={result}/></form></section>;
}
