"use client";

import Link from "next/link";
import { useState } from "react";
import { Badge } from "@/components/ui";
import { categoryPath } from "@/lib/catalog";
import { candidateStatusLabels, difficultyLabels, humanReviewLabels, questionTypeLabels, rubricLabels, sourceStatusLabels, sourceTypeLabels } from "@/lib/labels";
import type { Category, Competency } from "@/types/category";
import type { SourceCandidate, QuestionCandidate } from "@/types/source";
import type { EvaluationReview } from "@/types/evaluation";

export function SourceTable({ sources, categories }: { sources: SourceCandidate[]; categories: Category[] }) {
  const [items, setItems] = useState(sources);
  const [notice, setNotice] = useState("");
  return <><p className="notice mb-5">Synthetic source records and example.com URLs. No sources have been fetched.</p><div className="panel table-scroll"><table><caption className="sr-only">Mock source discovery queue</caption><thead><tr><th>Source</th><th>Suggested category</th><th>Relevance</th><th>Discovered</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map((source) => <tr key={source.id}><td><span className="font-medium block">{source.title}</span><span className="muted text-xs block mt-1">{sourceTypeLabels[source.sourceType]}</span><a href={source.url} target="_blank" rel="noreferrer" className="text-link text-xs break-all">{source.url}</a></td><td className="text-sm">{source.suggestedCategoryIds.map((id) => categoryPath(categories, id)).join(", ") || "Not assigned"}</td><td><span className="mono">{source.relevanceScore}</span><span className="muted text-xs"> / 100</span></td><td className="whitespace-nowrap text-sm">{source.discoveredAt.slice(0, 10)}</td><td><Badge tone={source.status === "discovered" ? "warning" : "neutral"}>{sourceStatusLabels[source.status]}</Badge></td><td>{source.status === "discovered" ? <button type="button" className="button button-small button-secondary" onClick={() => { setItems(items.map((item) => item.id === source.id ? { ...item, status: "screened" } : item)); setNotice(`Marked “${source.title}” as screened locally. Reload to reset.`); }}>Mark screened</button> : <span className="muted text-xs">No pending action</span>}</td></tr>)}</tbody></table></div><p role="status" className="muted text-sm mt-4">{notice}</p></>;
}

export function CandidateCards({ candidates, sources, categories, competencies }: { candidates: QuestionCandidate[]; sources: SourceCandidate[]; categories: Category[]; competencies: Competency[] }) {
  const [items, setItems] = useState(candidates);
  const [notice, setNotice] = useState("");
  return <><div className="space-y-5">{items.map((candidate) => <article className="panel section-padding" key={candidate.id}><div className="flex flex-wrap justify-between gap-4"><div><p className="eyebrow">Source · {sources.find((source) => source.id === candidate.sourceId)?.title}</p><h2 className="mt-2">{candidate.suggestedTitle}</h2></div><div className="text-right"><span className="mono text-2xl">{candidate.candidateScore}</span><p className="muted text-xs">Candidate score / 100</p></div></div><div className="flex flex-wrap gap-2 mt-4"><Badge tone={candidate.status === "needs_review" ? "warning" : "neutral"}>{candidateStatusLabels[candidate.status]}</Badge><Badge tone="accent">{questionTypeLabels[candidate.questionType]}</Badge><Badge>{difficultyLabels[candidate.difficulty]}</Badge>{candidate.competencyIds.map((id) => <Badge key={id}>{competencies.find((item) => item.id === id)?.name ?? id}</Badge>)}</div><p className="muted text-sm mt-4">{candidate.suggestedCategoryIds.map((id) => categoryPath(categories, id)).join(" · ")}</p><div className="candidate-copy"><div><h3>Suggested scenario</h3><p className="muted mt-2">{candidate.suggestedScenario}</p></div><div><h3>Suggested question</h3><p className="mt-2">{candidate.suggestedQuestion}</p></div></div><div className="flex flex-wrap gap-3"><button type="button" className="button button-secondary" onClick={() => { setItems(items.map((item) => item.id === candidate.id ? { ...item, status: item.status === "rejected" ? candidates.find((original) => original.id === item.id)!.status : "rejected" } : item)); setNotice("Candidate decision updated locally. No source or draft was changed."); }}>{candidate.status === "rejected" ? "Undo rejection" : "Reject"}</button>{candidate.draftProblemId && candidate.status !== "rejected" ? <Link href={`/admin/problems?problem=${candidate.draftProblemId}`} className="button button-primary">Review draft →</Link> : <span className="muted text-sm self-center">{candidate.status === "rejected" ? "Excluded from the local review queue" : "No draft yet · Authoring is not connected"}</span>}</div></article>)}</div><p className="muted text-sm mt-4" role="status">{notice}</p></>;
}

export function EvaluationCards({ reviews, rubricNames }: { reviews: EvaluationReview[]; rubricNames: Record<string, string> }) {
  const [items, setItems] = useState(reviews);
  return <div className="space-y-6">{items.map((review) => <article key={review.id} className="panel section-padding"><div className="flex flex-wrap justify-between gap-3"><div><p className="eyebrow">Drone Dynamics Adaptation</p><h2 className="mt-2">{review.id === "eval-alternative" ? "A valid alternative was missed" : "A tentative idea was over-interpreted"}</h2></div><Badge tone={review.status === "needs_review" ? "warning" : "success"}>{review.status === "needs_review" ? "Needs Review" : "Reviewed"}</Badge></div><h3 className="mt-6">User response</h3><blockquote className="response-quote">{review.userResponse}</blockquote><h3 className="mt-6 mb-3">Mock evaluator judgment</h3><div className="table-scroll"><table><thead><tr><th>Rubric node</th><th>Status</th><th>Evidence / explanation</th></tr></thead><tbody>{review.result.rubricAssessments.map((assessment) => <tr key={assessment.rubricNodeId}><td><span className="text-sm">{rubricNames[assessment.rubricNodeId]}</span><span className="mono muted text-xs block">{assessment.rubricNodeId}</span></td><td><Badge tone={assessment.status === "misconception" ? "warning" : "neutral"}>{rubricLabels[assessment.status]}</Badge></td><td className="text-sm muted">{assessment.evidence.map((evidence) => evidence.quote ?? evidence.messageId).join("; ") || "No evidence"}{assessment.explanation && <p className="mt-2">{assessment.explanation}</p>}</td></tr>)}</tbody></table></div><p className="notice mt-5">Review note: {review.reviewNote}</p>{review.result.needsEscalation && <p className="text-sm muted mt-3">Escalation requested in fixture: {review.result.escalationReason} No model will be called.</p>}<div className="mt-5 max-w-sm"><label htmlFor={`${review.id}-review`}>Human review (local only)</label><select id={`${review.id}-review`} value={review.humanReview} onChange={(event) => { const decision = event.target.value as EvaluationReview["humanReview"]; setItems(items.map((item) => item.id === review.id ? { ...item, humanReview: decision, status: decision === "not_reviewed" ? "needs_review" : "reviewed" } : item)); }}>{Object.entries(humanReviewLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></div><p className="text-xs muted mt-3" role="status">{humanReviewLabels[review.humanReview]} · Reload resets this decision.</p></article>)}</div>;
}
