'use client';
import { useEditorScroll } from './use-editor-scroll';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { saveProblemVersion,validateProblemVersion,publishVersion,createVersion,archiveProblem,createProblem } from '@/app/actions/admin';
import { Field,MultiSelect,JsonField,Feedback,useAdminMutation,formText } from './editor-fields';
import { EvaluationEditor } from './evaluation-editor';
import { categoryOptions } from '@/lib/catalog';
import { competencies } from '@/lib/competencies';
import { questionTypeLabels,difficultyLabels,versionStatusLabels,usageStatusLabels } from '@/lib/labels';
import { parseContent } from '@/lib/authoring/validation';
import type { ProblemEditorData,EditableContent,SourceLink } from '@/types/authoring';
import type { Category } from '@/types/category';
import type { SourceCandidate } from '@/types/source';

export function NewProblemForm() {
 const {run,pending,result}=useAdminMutation(),router=useRouter(),[open,setOpen]=useState(false),details=useEditorScroll<HTMLDetailsElement>(open);
 return <details ref={details} onToggle={e=>setOpen(e.currentTarget.open)} className="panel section-padding mb-5 scroll-mt-6"><summary className="text-link cursor-pointer font-medium">Create problem draft</summary><form className="space-y-4 mt-5" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form);run(()=>createProblem(formText(d,'slug'),formText(d,'title')),r=>{form.reset();if(details.current)details.current.open=false;router.push(`/admin/problems?problem=${r.id}`,{scroll:false});});}}><Field label="Title"><input name="title" required maxLength={500}/></Field><Field label="Problem URL slug"><input name="slug" required maxLength={200} pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="a-new-interview-scenario"/></Field><button className="button button-primary" disabled={pending} type="submit">Create problem draft</button><Feedback result={result}/></form></details>;
}
export function ProblemEditor({data,categories,sources}:{data:ProblemEditorData;categories:Category[];sources:SourceCandidate[]}) {
 const editorRef=useEditorScroll<HTMLElement>();
 const [content,setContent]=useState(()=>parseContent(data.problem)),[evaluation,setEvaluation]=useState(data.evaluation),[links,setLinks]=useState(data.sources);
 const [status,setStatus]=useState(data.version.status==='needs_review'?'needs_review':'draft'),[reviewed,setReviewed]=useState(false),[touched,setTouched]=useState(false);
 const [baseline]=useState(()=>JSON.stringify([parseContent(data.problem),data.evaluation,data.sources,data.version.status==='needs_review'?'needs_review':'draft']));
 const dirty=touched||JSON.stringify([content,evaluation,links,status])!==baseline,readonly=!!data.version.publishedAt;
 const {run,pending,result}=useAdminMutation(),router=useRouter();
 const update=<K extends keyof EditableContent>(key:K,value:EditableContent[K])=>{setContent({...content,[key]:value});setReviewed(false);};
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return ()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const options=categoryOptions(categories).map(c=>({id:c.id,name:'— '.repeat(c.depth)+c.name}));
 return <><section ref={editorRef} className="panel section-padding mb-6 scroll-mt-6"><p className="eyebrow">Version / publication</p><div className="flex flex-wrap justify-between items-center gap-4 mt-3"><p>Version {data.version.version} · {versionStatusLabels[data.version.status]} · <span role="status">{dirty?'Unsaved changes':'Saved'}</span></p><div className="flex flex-wrap gap-3"><Link href="/admin/problems" className="button button-secondary" onClick={e=>{if(pending||(dirty&&!window.confirm('Discard unsaved changes and close the editor?')))e.preventDefault();}}>Close editor</Link><Link href={`/admin/problems/${data.problem.id}/preview?version=${data.version.id}`} className="button button-secondary" target="_blank" rel="noreferrer">Preview as user ↗</Link>{readonly&&<button type="button" className="button button-primary" disabled={pending} onClick={()=>run(()=>createVersion(data.problem.id),r=>router.push(`/admin/problems?problem=${data.problem.id}&version=${r.id}`,{scroll:false}))}>Create new version</button>}{data.problem.status!=='archived'&&<button type="button" className="button button-secondary" disabled={pending||dirty} onClick={()=>run(()=>archiveProblem(data.problem.id))}>Archive problem</button>}</div></div><p className="muted text-xs mt-3">Preview opens the saved version. Published content and evaluation material are immutable. New drafts copy the current published version. Save your changes before validation or publication.</p><nav aria-label="Version history" className="flex flex-wrap gap-3 mt-4">{data.history.map(v=><Link key={v.id} scroll={false} href={`/admin/problems?problem=${data.problem.id}&version=${v.id}`} className="text-link text-sm" aria-current={v.id===data.version.id?'page':undefined}>Version {v.version} · {versionStatusLabels[v.status]}</Link>)}</nav></section>
 <form onSubmit={e=>{e.preventDefault();run(()=>saveProblemVersion(data.version.id,data.version.revision,content,evaluation,links,status),()=>router.replace('/admin/problems?saved=draft'));}}><div className="editor-grid"><div className="space-y-6 min-w-0"><fieldset disabled={pending||readonly} onChange={()=>{setTouched(true);setReviewed(false);}} className="space-y-6 min-w-0"><section className="panel section-padding"><p className="eyebrow">Public content</p><h2 className="mt-2">Draft editor</h2><div className="space-y-4 mt-5">{([{key:'title',label:'Title',rows:1},{key:'shortDescription',label:'Short description',rows:2},{key:'scenario',label:'Scenario',rows:5},{key:'question',label:'Question',rows:3}] as const).map(f=><Field key={f.key} label={f.label}><textarea rows={f.rows} required={f.key==='title'} maxLength={f.key==='title'?500:30000} value={content[f.key]} onChange={e=>update(f.key,e.target.value)}/></Field>)}<Field label="Assumptions" help="One assumption per line."><textarea rows={4} value={content.assumptions.join('\n')} onChange={e=>update('assumptions',e.target.value.split('\n'))}/></Field><Field label="Tags" help="One tag per line."><textarea rows={3} value={content.tags.join('\n')} onChange={e=>update('tags',e.target.value.split('\n'))}/></Field></div></section>
 <section className="panel section-padding space-y-4"><h2>Classification</h2><Field label="Primary category"><select value={content.primaryCategoryId} onChange={e=>{const id=e.target.value;setContent({...content,primaryCategoryId:id,categoryIds:id?[...new Set([...content.categoryIds,id])]:content.categoryIds});setReviewed(false);}}><option value="">Not assigned yet</option>{options.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><MultiSelect label="Secondary categories" options={options.filter(c=>c.id!==content.primaryCategoryId)} value={content.categoryIds.filter(id=>id!==content.primaryCategoryId)} onChange={ids=>update('categoryIds',[...(content.primaryCategoryId?[content.primaryCategoryId]:[]),...ids])}/><Field label="Question type"><select value={content.questionType} onChange={e=>update('questionType',e.target.value as EditableContent['questionType'])}>{Object.entries(questionTypeLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><MultiSelect label="Competencies" options={competencies} value={content.competencyIds} onChange={ids=>update('competencyIds',ids)}/><Field label="Difficulty"><select value={content.difficulty} onChange={e=>update('difficulty',e.target.value as EditableContent['difficulty'])}>{Object.entries(difficultyLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field></section>
 <section className="panel section-padding"><h2>Visualization</h2><p className="muted text-sm mt-2 mb-4">Structured flow metadata only. Text is rendered safely; scripts, HTML and executable SVG are not supported.</p><JsonField label="Visualization metadata" value={content.visualization} help='Use null for no diagram, or {"kind":"flow","title":"System","caption":"Flow overview","nodes":[{"id":"input","label":"Input","detail":"Recent history"}]}.' onChange={v=>update('visualization',v as EditableContent['visualization'])}/></section>
 <section className="panel section-padding"><h2>Sources / provenance</h2><p className="muted text-sm mt-2">Optional references for this version. Usage status is an editorial record, not an automatic rights decision.</p>{links.map((link,index)=>{const source=sources.find(s=>s.id===link.sourceId);return <div className="public-preview space-y-3" key={index}><Field label="Source"><select value={link.sourceId} onChange={e=>setLinks(links.map((v,i)=>i===index?{...v,sourceId:e.target.value}:v))}>{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></Field>{source&&<div className="muted text-xs"><a className="text-link break-all" href={source.url} target="_blank" rel="noreferrer">{source.url}</a><p className="mt-2">{usageStatusLabels[source.usageStatus]} · {source.sourceType}</p><p>{source.provenanceNotes||source.notes}</p></div>}<Field label="Relation"><select value={link.relationType} onChange={e=>setLinks(links.map((v,i)=>i===index?{...v,relationType:e.target.value as SourceLink['relationType']}:v))}>{['inspired_by','adapted_from','reference','validation_source'].map(id=><option key={id} value={id}>{id.replaceAll('_',' ')}</option>)}</select></Field><Field label="Attribution note"><textarea rows={2} value={link.attributionNote} onChange={e=>setLinks(links.map((v,i)=>i===index?{...v,attributionNote:e.target.value}:v))}/></Field><button type="button" className="button button-small button-secondary" onClick={()=>setLinks(links.filter((_,i)=>i!==index))}>Remove source link</button></div>;})}<button type="button" className="button button-secondary mt-4" disabled={!sources.some(s=>!links.some(l=>l.sourceId===s.id))} onClick={()=>{const next=sources.find(s=>!links.some(l=>l.sourceId===s.id));if(next)setLinks([...links,{sourceId:next.id,relationType:'reference',attributionNote:''}]);}}>Add source link</button></section>
 </fieldset>
 {/* Review controls stay outside the content fieldsets so approval does not mark the draft dirty. */}
 {!readonly&&<section className="panel section-padding editor-publication-controls"><div className="editor-action-row"><Field label="Draft status"><select value={status} disabled={pending} onChange={e=>{setStatus(e.target.value);setTouched(true);setReviewed(false);}}><option value="draft">Draft</option><option value="needs_review">Needs Review</option></select></Field><div className="editor-action-buttons"><button type="submit" disabled={pending} className="button button-primary">{pending?'Saving…':'Save draft'}</button><button type="button" disabled={pending||dirty} className="button button-secondary" onClick={()=>run(()=>validateProblemVersion(data.problem.id,data.version.id))}>Validate saved draft</button></div></div><div className="editor-action-row mt-5"><Field label="Human review"><select value={reviewed?'reviewed':'pending'} disabled={pending||dirty} onChange={e=>setReviewed(e.target.value==='reviewed')}><option value="pending">Review required</option><option value="reviewed">I have reviewed this saved version</option></select></Field><div className="editor-action-buttons"><button type="button" disabled={pending||dirty||!reviewed} className="button button-primary" onClick={()=>run(()=>publishVersion(data.problem.id,data.version.id,data.version.revision))}>Publish version {data.version.version}</button></div></div>{dirty&&<p className="muted text-sm mt-3">You have unsaved changes. Save this draft to validate and publish it.</p>}</section>}<Feedback result={result}/></div><fieldset disabled={pending||readonly} onChange={()=>{setTouched(true);setReviewed(false);}} className="min-w-0"><EvaluationEditor value={evaluation} onChange={v=>{setEvaluation(v);setReviewed(false);}}/></fieldset></div></form></>;
}
