'use client';
import { saveSource } from '@/app/actions/admin';
import { categoryOptions } from '@/lib/catalog';
import { sourceTypeLabels,sourceStatusLabels,usageStatusLabels } from '@/lib/labels';
import type { SourceCandidate } from '@/types/source';
import type { Category } from '@/types/category';
import { Field,MultiSelect,Feedback,useAdminMutation,formText,formList,formScore } from './editor-fields';
export function SourceEditor({source,categories,onSaved}:{source?:SourceCandidate;categories:Category[];onSaved:(id:string)=>void}) {
 const {run,pending,result}=useAdminMutation();
 return <section className="panel section-padding mt-5"><h2>{source?'Edit source':'Add source'}</h2><p className="muted text-sm mt-2">Record a reference manually. A public URL does not establish permission to reuse its content.</p><form className="space-y-4 mt-5" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);run(()=>saveSource(source?.id??null,{title:formText(d,'title'),url:formText(d,'url'),sourceType:formText(d,'type'),status:formText(d,'status'),suggestedCategoryIds:formList(d,'categories'),relevanceScore:formScore(d,'score'),usageStatus:formText(d,'usage'),notes:formText(d,'notes'),provenanceNotes:formText(d,'provenance'),usageNotes:formText(d,'usageNotes')}),r=>r.id&&onSaved(r.id));}}><fieldset disabled={pending} className="space-y-4"><Field label="Title"><input name="title" defaultValue={source?.title} required maxLength={500}/></Field><Field label="URL"><input name="url" type="url" defaultValue={source?.url} required maxLength={2048}/></Field><div className="grid sm:grid-cols-2 gap-4"><Field label="Source type"><select name="type" defaultValue={source?.sourceType??'paper'}>{Object.entries(sourceTypeLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><Field label="Status"><select name="status" defaultValue={source?.status??'discovered'}>{Object.entries(sourceStatusLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field></div><MultiSelect label="Suggested categories" name="categories" value={source?.suggestedCategoryIds??[]} options={categoryOptions(categories).map(c=>({id:c.id,name:'— '.repeat(c.depth)+c.name}))}/><Field label="Relevance score (optional)"><input name="score" type="number" min={0} max={100} step={1} defaultValue={source?.relevanceScore??''}/></Field><Field label="Usage status"><select name="usage" defaultValue={source?.usageStatus??'unknown'}>{Object.entries(usageStatusLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field>{([{name:'notes',label:'Notes',value:source?.notes},{name:'provenance',label:'Provenance notes',value:source?.provenanceNotes},{name:'usageNotes',label:'Usage notes',value:source?.usageNotes}]).map(f=><Field key={f.name} label={f.label}><textarea name={f.name} rows={3} maxLength={10000} defaultValue={f.value}/></Field>)}<button className="button button-primary" type="submit">{pending?'Saving…':'Save source'}</button></fieldset><Feedback result={result}/></form></section>;
}
