import Link from 'next/link';
import { Badge } from '@/components/ui';
import type { ProblemPublic } from '@/types/problem';
import type { AttemptSession } from '@/types/attempt';

export function ReviewContent({ problem, attempt }: { problem: ProblemPublic; attempt: AttemptSession }) {
  const userMessages = attempt.messages.filter((message) => message.role === 'user');
  return <><div className="review-banner"><div><Badge tone="success">Interview finished</Badge><h1 className="mt-4">A moment to connect the dots.</h1><p className="muted mt-3">{problem.title} · Version {problem.version} · Saved conversation, not an automated score.</p></div><div className="review-hint-count"><strong>{attempt.hintsUsed.length}</strong><span>Hints used</span></div></div>
    <div className="review-grid"><div className="space-y-6"><section className="panel section-padding"><p className="eyebrow">Reflection</p><h2 className="mt-2">Reasoning summary</h2><p className="muted mt-4 leading-relaxed">Review the reasoning you recorded during this interview. Automated assessment is not available yet.</p><div className="mt-6"><h3>Your contributions</h3>{userMessages.length ? <ul className="reasoning-list mt-3">{userMessages.map((message) => <li key={message.id} className="whitespace-pre-wrap">{message.content}</li>)}</ul> : <p className="muted mt-2">You finished this interview without adding a response.</p>}</div></section><section className="panel section-padding"><p className="eyebrow">Reference</p><h2 className="mt-2">Reference answer</h2><p className="mt-4 leading-8">Reference answers are not available yet. Your saved conversation and requested hints remain accessible here.</p></section></div><div className="space-y-6"><section className="key-idea"><p className="eyebrow">Session saved</p><p className="text-xl leading-relaxed mt-3 font-medium">Your reasoning is ready to revisit.</p></section><section className="panel section-padding"><h2>Hints used</h2>{attempt.hintsUsed.length ? <ul className="reasoning-list mt-4">{attempt.hintsUsed.map((hint) => <li key={hint.hintId}>{hint.displayedText}</li>)}</ul> : <p className="muted text-sm mt-2">You did not request a hint.</p>}</section><section className="panel section-padding"><h2>Conversation</h2><div className="space-y-3 mt-4">{attempt.messages.map((message) => <article key={message.id} className={`message message-${message.role}`}><p className="message-label">{message.role === 'user' ? 'You' : message.role === 'system_hint' ? 'Hint' : 'Interviewer'}</p><p className="whitespace-pre-wrap">{message.content}</p></article>)}</div></section></div></div><div className="flex flex-wrap gap-3 mt-8"><Link href={`/problems/${problem.slug}`} className="button button-primary">Practice again</Link><Link href="/review" className="button button-secondary">Interview history</Link><Link href="/problems" className="button button-secondary">Explore more problems</Link></div></>;
}
