import { readFile, writeFile } from 'node:fs/promises';
const seed = JSON.parse(await readFile(new URL('../supabase/seed-data.json', import.meta.url), 'utf8'));
const quote = (value) => value == null ? 'null' : `'${String(value).replaceAll("'", "''")}'`;
const json = (value) => value == null ? 'null' : `${quote(JSON.stringify(value))}::jsonb`;
const array = (values) => `array[${values.map(quote).join(', ')}]::text[]`;
const lines = ['-- Generated by pnpm seed:generate from the preserved UI fixtures.', '-- Development content only. Reruns insert missing records and never overwrite edited data.', 'begin;', 'set constraints all deferred;'];
function insert(table, fields, values, existence) {
  lines.push(`insert into public.${table} (${fields.join(', ')})\nselect ${values.join(', ')}\nwhere not exists (select 1 from public.${table} where ${existence})\non conflict do nothing;`);
}
seed.categories.forEach((c, index) => insert('categories', ['id', 'slug', 'name', 'parent_id', 'description', 'sort_order'], [quote(c.id), quote(c.slug), quote(c.name), quote(c.parentId), quote(c.description), index], `id = ${quote(c.id)}`));
for (const p of seed.problems) {
  insert('problems', ['id', 'slug', 'status', 'current_version_id', 'published_at'], [quote(p.id), quote(p.slug), quote(p.status), quote(p.versionId), quote(p.publishedAt)], `id = ${quote(p.id)}`);
  insert('problem_versions', ['id', 'problem_id', 'version_number', 'title', 'short_description', 'scenario', 'question', 'assumptions', 'visualization', 'competency_ids', 'difficulty', 'tags', 'origin'], [quote(p.versionId), quote(p.id), p.version, quote(p.title), quote(p.shortDescription), quote(p.scenario), quote(p.question), array(p.assumptions), json(p.visualization), array(p.competencyIds), quote(p.difficulty), array(p.tags), quote(p.origin)], `id = ${quote(p.versionId)}`);
  for (const id of p.categoryIds) insert('problem_categories', ['problem_id', 'category_id', 'is_primary'], [quote(p.id), quote(id), id === p.primaryCategoryId ? 'true' : 'false'], `problem_id = ${quote(p.id)} and category_id = ${quote(id)}`);
}
for (const s of seed.evaluationPackages) insert('problem_evaluation_packages', ['problem_version_id', 'reference_answer', 'reasoning_rubric', 'acceptable_alternative_approaches', 'misconceptions', 'hint_ladder', 'completion_criteria', 'evaluation_examples'], [quote(s.problemVersionId), quote(s.referenceAnswer), json(s.reasoningRubric), json(s.acceptableAlternativeApproaches), json(s.misconceptions), json(s.hintLadder), json(s.completionCriteria), json(s.evaluationExamples)], `problem_version_id = ${quote(s.problemVersionId)}`);
lines.push('commit;', '');
await writeFile(new URL('../supabase/seed.sql', import.meta.url), lines.join('\n\n'));
console.log(`Generated seed: ${seed.categories.length} categories, ${seed.problems.length} problems, ${seed.evaluationPackages.length} private packages.`);
